### ISSUE TITLE
communication typeerror

### ISSUE THREAD

**Issue by adaja01** [Bluesheep33/Palcord#25]
when starting, communication works well.
but after a while, client returns typeerror when trying to retrieve the discord channel to send the message to

**Comment by adaja01** [comment]
Issue doesn't appear anymore

**Comment by adaja01** [comment]
appeared again:

2|index    | TypeError: Cannot read properties of undefined (reading 'channels')
2|index    |     at relayServerMessage (/home/discord/palcord/src/server_events/relayServerMessage.js:3:34)
2|index    |     at module.exports (/home/discord/palcord/src/handlers/serverLogLineHandler.js:16:17)
2|index    |     at Interface.<anonymous> (/home/discord/palcord/src/services/serverLogService.js:45:9)
2|index    |     at Interface.emit (node:events:519:28)
2|index    |     at [_onLine] [as _onLine] (node:internal/readline/interface:416:12)
2|index    |     at [_normalWrite] [as _normalWrite] (node:internal/readline/interface:610:22)
2|index    |     at ReadStream.ondata (node:internal/readline/interface:243:23)
2|index    |     at ReadStream.emit (node:events:519:28)
2|index    |     at addChunk (node:internal/streams/readable:559:12)
2|index    |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
